# Site

remote_theme: wowthemesnet/mediumish-theme-jekyll


name: "INFO 1121"
title: "Spring 2021 Project Showcase"
description: "Student projects exploring current topics in information science and interaction design"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '' 
google_analytics: 'UA-179402368-1'
disqus: '1121portfolios'
include: ["_pages"]
permalink: /:title/


lsi: false
safe: true
source: S21-1121-Projects
incremental: false
highlighter: rouge

gist:
  noscript: false


# Authors
authors:
  sal:
    name: Laura
    display_name: The Professor
    email: laura.devendorf@colorado.edu
    description: "Posted by the professor of this course"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
